### ISSUE TITLE
Unsupported driver [cassandra]

### ISSUE THREAD

**Issue by newbielinuxuser** [ShahinSorkh/laravel-cassandra#10]
Using Laravel 5.5.28 fresh installation, followed the steps, and here it goes...

errors pops up saying undefined index : database at vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php

`
config/database.php 
`
> 'cassandra' => [
>     'driver' => 'cassandra',
>     .....
>     'keyspace' => env('DB_DATABASE', 'cassandra_db'),
> ],

And so I tried adding in 'database' 
`
config/database.php
`
> 'cassandra' => [
>     'driver' => 'cassandra',
>     .......
>     'database' => env('DB_DATABASE', 'cassandra_db'),
>     'keyspace' => env('DB_DATABASE', 'cassandra_db'),
> ],
> 

And now it says unsupported driver[cassandra]. to me it seems like it is still creating a single connection without using cassandra driver and it is using the default createConnection which is simply not in the switch case in that particular file

`
vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php
`
> protected function createConnection($driver, $connection, $database, $prefix = '', array $config = [])
> ....
> switch ($driver) {
>             case 'mysql':
>                 return new MySqlConnection($connection, $database, $prefix, $config);
>             case 'pgsql':
>                 return new PostgresConnection($connection, $database, $prefix, $config);
>             case 'sqlite':
>                 return new SQLiteConnection($connection, $database, $prefix, $config);
>             case 'sqlsrv':
>                 return new SqlServerConnection($connection, $database, $prefix, $config);
> }
> ....

**Comment by athe0i** [comment]
@newbielinuxuser for now you can actually use driver => `Cassandra`, think it was typo at some point :)

**Comment by ShahinSorkh** [comment]
This has been fixed in 8a54fdbf.
I have made a tag `v1.1.2` so you can update your dependencies using composer.
It's prefferd to use `master-dev` version since the package is not stable yet.
