### ISSUE TITLE
do it can support this plugin?

### ISSUE THREAD

**Issue by vahidalvandi** [ShahinSorkh/laravel-cassandra#3]
https://github.com/lazychaser/laravel-nestedset

**Comment by ShahinSorkh** [comment]
As

> This is a Laravel 4-5 package for working with trees in relational databases.

this package will never fit for it.

Cassandra is a noSQL (say not-relational) database and this package is a wrapper around datastax driver for cassandra, then, _NO_.

**Comment by vahidalvandi** [comment]
thanks
